#!/bin/bash
#PBS -l select=1:ncpus=40:mem=12gb
#PBS -l walltime=240:00:00
#PBS -j oe
#PBS -q fthpc
#PBS -N xcompress
#PBS -M ptriant@g.clemson.edu
#pbs -m abe
module load gcc/4.8.1
module load mpich
module load python/3.4

cd /home/ptriant/Research/zfp/zfp-python

tol=1E-9
file=/zfs/fthpc/plascomcm/inputs/pavlo_runs/plascomcm_run_data/$tol/zfp-0.5.1/1000.txt

python compress_zfp.py $tol 1000 > $file



