#!/bin/bash
#PBS -l select=1:ncpus=40:mem=12gb
#PBS -l walltime=240:00:00
#PBS -j oe
#PBS -q fthpc
#PBS -N xcompress
#PBS -M ptriant@g.clemson.edu
#pbs -m abe
module load gcc/4.8.1
module load mpich
module load python/3.4

cd /home/ptriant/Research/zfp/zfp-python

tol=1E-6
compressor=zfp-0.5.4
simple_dll=./$compressor/examples/simple.dll
file=/zfs/fthpc/plascomcm/inputs/pavlo_runs/plascomcm_run_data/$tol/$compressor/1000.txt

python compress_zfp.py $tol 1000 $simple_dll > $file



